apiVersion: v1
kind: Service
metadata:
   name: spring-hello-app-svc
   namespace: akshay-namespace
spec:
   ports:
   -  name: http
      port: 8080
      targetPort: 8080
   selector:
      app: spring-hello-app
   type: ClusterIP
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: spring-hello-app-dep
   namespace: akshay-namespace
spec:
   replicas: 2
   selector:
      matchLabels:
         app: spring-hello-app
   template:
      metadata:
         labels:
            app: spring-hello-app
      spec:
         containers:
         -  image: mkt-eng-dev.common.repositories.cloud.sap/mkt/spring-hello-app
#         -  image: spring-hello-app
#            name: spring-hello-app
            ports:
            -  containerPort: 8080
#         imagePullSecrets:
#         -  name: akshay-docker-secret